[package]
name = "utils"
version = "0.1.0"
authors = [ "ChainSafe Systems <info@chainsafe.io>" ]
edition = "2018"

[dependencies]
dirs = "3.0"
serde = "1.0"
toml = "0.5.5"

[dev-dependencies]
serde_derive = "1.0"
