[package]
name = "db"
version = "0.1.0"
authors = [ "ChainSafe Systems <info@chainsafe.io>" ]
edition = "2018"

[dependencies]
encoding = { package = "forest_encoding", path = "../../encoding" }
parking_lot = "0.10.0"
rocksdb = { version = "0.14.0", optional = true }
thiserror = "1.0"
